RSDK-2483: Encoder API SDK changes (Python)
viamrobotics/viam-python-sdk pull request #256
Opened 2023-04-11 20:57 UTC by martha-johnston

This change adds support for the new encoder API in the Python SDK. All of the tests in `test_encoder.py` pass successfully, however there is a consistent IDE error of a type mismatch whenever using the PositionType enum. It shouldn't be an actual issue (as it's not causing any tests to fail) but for reference, those errors occur at the following locations:
- `src/viam/components/encoder/service.py`, line 49, `request.position_type`, and line 51, `pos_type`
- `tests/mocks/components.py`, line 442, `return ... self.position_type`
- `examples/server/v1/components.py`, line 454, `return ... self.position_type`

2023-04-11 21:21 UTC, randhid reviewed
Few nits.

2023-04-11 21:21 UTC, randhid commented on src/viam/components/encoder/encoder.py
> +                   for an incremental encoder or degrees for an absolute encoder.
Just so we avoid `incremental` model language confustion
```suggestion
                   for a relative encoder or degrees for an absolute encoder.
```

2023-04-17 19:37 UTC, njooma requested changes

2023-04-17 19:37 UTC, njooma commented on src/viam/components/encoder/encoder.py
> +
This should have a comment describing the parameter `position_type` and what it is/used for

2023-04-17 19:59 UTC, njooma requested changes
So the test is failing because evidently python 3.9 is being stricter with types. So everywhere you take `PositionType` as a param/return, you should make it `PositionType.ValueType`. 

[nit] Also, be sure to organize your imports. You can do so in VS Code by pressing Option+Shift+O

2023-04-19 16:16 UTC, njooma requested changes

2023-04-19 16:16 UTC, njooma commented on src/viam/components/encoder/encoder.py
> +        (ticks away from a zero position) for PositionTypeTICKS or absolute units (degrees along a circle) for PositionTypeDEGREES.
```suggestion
        (ticks away from a zero position) for ``PositionType.TICKS`` or absolute units (degrees along a circle) for ``PositionType.DEGREES``.
```

2023-04-19 21:10 UTC, njooma approved these changes

2023-04-19 21:23 UTC, merged