RSDK-3292 - fix example python movement sensors
viamrobotics/viam-python-sdk pull request #308
Opened 2023-06-02 14:18 UTC by jckras

Follow-up work to be done: https://viam.atlassian.net/browse/RSDK-3403

2023-06-02 14:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/viamrobotics/viam-python-sdk?pullRequest=308) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/viamrobotics/viam-python-sdk?pullRequest=308) before we can accept your contribution.<br/><hr/>**Julie krasnick** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/viamrobotics/viam-python-sdk?pullRequest=308) it.</sub>

2023-06-02 16:07 UTC, stuqdog requested changes
A couple small suggestions, but otherwise this looks great! thanks for putting it together :)

2023-06-02 16:07 UTC, stuqdog commented on tests/mocks/components.py
> +
(nit) probably we should get rid of this newline

2023-06-02 16:07 UTC, stuqdog commented on tests/test_robot.py
> +    # ResourceName(namespace="rdk", type="component", subtype="sensor", name="movement_sensor1"),
As a general policy, I think it's best to not have commented code committed. It is often unclear what purpose it serves/used to serve, and there's no validation that the code still works as expected. Probably best to get rid of this entirely.

2023-06-05 15:56 UTC, jckras commented
Re-requested review after updating the tests to account for the dedupe done in generate metadata. Also added dedupe in generateStatus

2023-06-05 18:25 UTC, cheukt approved these changes
Looks great! small nit

2023-06-05 18:25 UTC, cheukt commented on tests/test_robot.py
> +            assert list(response.status) == (STATUSES)
extra parenthesis?

2023-06-05 18:38 UTC, stuqdog approved these changes
LGTM!

2023-06-05 20:00 UTC, merged