Rsdk 7188 add app wrappers
viamrobotics/viam-python-sdk pull request #614
Opened 2024-05-14 18:32 UTC by purplenicole730

2024-05-15 12:21 UTC, stuqdog requested changes
Nice, this is looking good overall! Just a couple nits and one slight "gotcha" of a refactor request

2024-05-15 12:21 UTC, stuqdog commented on src/viam/app/app_client.py
> +                added to. Must match `resource_id`.
(nit) `s/resource_id/old_resource_id`

2024-05-15 12:21 UTC, stuqdog commented on src/viam/app/app_client.py
> +                Must match `resource_id`.
(nit) `s/resource_id/new_resource_id`

2024-05-15 14:14 UTC, purplenicole730 commented on src/viam/app/app_client.py
> +                to. Must match `resource_id`.
Yeah, that makes sense. I was just thinking about the fact that it was added to the resource_type previously, but we are removing it so "being removed from" makes a lot of sense!

2024-05-16 13:09 UTC, stuqdog approved these changes
Nice, one nit otherwise looks great! Thanks for also going back and updating docstring comments from previously implemented methods, much appreciated :)

2024-05-16 13:09 UTC, stuqdog commented on src/viam/app/app_client.py
> +            id = await cloud.get_user_id_by_email("youremail@email.com")`
(nit) we still have this trailing ` here, which we should probably get rid of.

2024-05-16 16:13 UTC, njooma approved these changes

2024-05-16 16:27 UTC, merged