DOCS-2313: Clean up gantry and arm pages for docs parsing
viamrobotics/viam-python-sdk pull request #631
Opened 2024-06-04 21:15 UTC by sguequierre

[whole ticket is WIP] 

Questions: 
* Should I leave the extra and timeout parameters out still? Figured it might help with parsing and couldn't hurt to have description in these docs
* Is there any way to manually add a link for a type in the docstrings?

2024-06-05 16:39 UTC, andf-viam commented
Great start! Thanks @sguequierre !

- Yes, you should omit `timeout` and `extra`. We scrape these from the initial usage declaration of the method (first line) and not from the **Properties** section. I believe the intend is to omit these SDK-wide. Only `motion` included them explicitly, and should likely remove them also.
- Yes, for docs.viam.com. We can manually add a link using the `python_datatype_links` array in `update_sdk_methods.py`. For the upstream SDK docs site though, I'd ask the team here: "any way to manually provide links here outside of the automated linking that occurs during `make documentation`?" Sierra, you made an excellent observation that some existing generated links by this step appear incorrect: "the resource type links are a bit tricky, as far as I can tell this is done automatically by some scraper/parser and it is not always correct (See base [Properties](https://python.viam.dev/autoapi/viam/components/base/client/index.html#viam.components.base.client.BaseClient.get_properties) linking to audioinput).

2024-06-05 18:13 UTC, stuqdog requested changes
Nice, thanks for doing this! A couple small things, but otherwise this looks great.

2024-06-06 15:48 UTC, sguequierre commented on src/viam/components/arm/arm.py
> +            timeout (Optional[float]): An option to set how long to wait (in seconds) before calling a time-out and closing the underlying RPC call.
Ok, thank you!

2024-06-10 13:45 UTC, stuqdog commented
> > * any way to manually provide links here outside of the automated linking that occurs during `make documentation`?
> 
> @stuqdog do you know about this? No worries if not

Ah good question! I'm not sure, but @njooma might know?

2024-06-11 16:17 UTC, andf-viam approved these changes
LGTM, thank you!

2024-06-11 19:27 UTC, merged