DOCS-2899: Clean up data client API code samples
viamrobotics/viam-python-sdk pull request #729
Opened 2024-09-13 15:33 UTC by sguequierre

* tested all of these and found some issues
* incorporating fixes -- will be mirrored in docs

2024-09-13 15:33 UTC, sguequierre commented on src/viam/app/data_client.py
> +            binary_data = await data_client.binary_data_by_ids(my_ids)
```suggestion
            binary_data = await data_client.delete_binary_data_by_ids(my_ids)
```

2024-09-16 15:11 UTC, njooma approved these changes
I trust you on this one

2024-09-16 16:07 UTC, npentrel requested changes
Let's hold off on merging for a bit please

2024-09-19 11:33 UTC, npentrel approved these changes

2024-09-19 14:20 UTC, merged