RSDK-9146: Change Python TabularDataBySQL/MQL return type to raw BSON
viamrobotics/viam-python-sdk pull request #774
Opened 2024-10-25 14:47 UTC by jckras

For context: The return type of the `TabularDataBySQL/MQL` proto has changed to return both a list of structs, the existing return type, and also a list of bytearrays that represent BSON.

- Added a required dependency to `pymongo` to use the `BSON` library
- `BSON` provides a `decode()` function for converting lists of byte sequences into Python dictionaries. 

**Testing**:
- I ensured that date fields are returned as native Python `datetime` objects instead of strings by running tabular_data_by_mql against real tabular data on viam-dev and printed the decoded data and their types: 
        <img width="495" alt="Screenshot 2024-10-29 at 11 56 09 AM" src="https://github.com/user-attachments/assets/6a8cc4a2-6a01-4ed0-94f5-3f955eceb3c9">
- Updated the `TABULAR_QUERY_RESPONSE` testing data to include datetime objects, as the Python SDK will receive date fields in this format.

2024-10-29 15:57 UTC, jckras commented
- bson.decode() returns datetime objects which I confirmed when running `tabular_data_by_mql` against real tabular data on viam-dev. 
<img width="495" alt="Screenshot 2024-10-29 at 11 56 09 AM" src="https://github.com/user-attachments/assets/6a8cc4a2-6a01-4ed0-94f5-3f955eceb3c9">

2024-10-30 17:44 UTC, njooma requested changes
nearly there! only one change

2024-10-30 17:44 UTC, njooma commented on pyproject.toml
> +	"pymongo>=4.10.1"
This isn't a `dev-dependency`, but rather an ACTUAL `dependency` and should be moved up into that section

2024-10-31 14:43 UTC, stuqdog approved these changes

2024-11-01 16:17 UTC, njooma approved these changes

2024-11-01 16:22 UTC, merged